bot:
    owners: ["678402714765361182"]
    presence:
        enabled: true
        status: dnd
        interval: 10000
        activity:
            [
                { "name": "your Favorite Songs", "type": "PLAYING" },
                { "name": "<clientname> Radio!", "type": "LISTENING" },
                { "name": "<usersize> Users!", "type": "LISTENING" },
                { "name": "version 4.0", "type": "PLAYING" },
                { "name": "with <guildsize> Servers!", "type": "PLAYING" },
                { "name": "<channelsize> Channels!", "type": "WATCHING" },
            ]
    command:
        prefix: "!"
        disable_message: false
        cooldown_message: You are on `<duration>` cooldown!
        register_specific_commands:
            enabled: false
            commands: ["help", "ping", "info"]
    log:
        command: "1332426115788308583"
        server: "1332426130703257744"

music:
    enabled: true
    image: "https://localhost:8080/assets/music.gif"
    lavalink:
        default_search: spsearch
        nodes:
            [
                {
                    "identifier": "Pepper 1",
                    "host": "lavalink.muralianand.in",
                    "port": 25773,
                    "password": "4Vzm^mZw2CJG@P7pMM5$",
                    "priority": 1,
                    "secure": true,
                    "retryAmount": 1000,
                    "retrydelay": 10000,
                    "resumeStatus": false,
                    "resumeTimeout": 1000,
                    "requestTimeout": 10000,
                },
                {
                    "identifier": "Pepper 2",
                    "host": "lavalink.jirayu.net",
                    "port": 13592,
                    "password": "youshallnotpass",
                    "priority": 2,
                    "secure": false,
                    "retryAmount": 1000,
                    "retrydelay": 10000,
                    "resumeStatus": false,
                    "resumeTimeout": 1000,
                    "requestTimeout": 10000,
                },
            ]

content:
    text:
        no_music_playing: No Music Playing Right Now 😔
    embed:
        color:
            default: Burple
            success: Green
            error: Red
            info: Blue
            warning: Yellow
        no_music_playing:
            author:
                name: "No song playing currently"
                icon_url: https://media.discordapp.net/attachments/1100136924305440829/1118029575755145277/image.png?ex=67950cee&is=6793bb6e&hm=d6a106740f477165d7ffb529920436f29051152b8642c566689ae4eacc52b857&=&format=webp&quality=lossless&width=1232&height=806
            image: https://media.discordapp.net/attachments/1100136924305440829/1118029575755145277/image.png?ex=67950cee&is=6793bb6e&hm=d6a106740f477165d7ffb529920436f29051152b8642c566689ae4eacc52b857&=&format=webp&quality=lossless&width=1232&height=806
